apiVersion: apps/v1
kind: Deployment
metadata:
  name: java-dev
spec:
  template:
    metadata:
      name: pod-java-dev
      labels:
        app: lable-pod-java-dev
    spec:
      containers:
        - name: container-java-dev
          image:  alexandreponte/validadorcpfjava
          ports:
            - containerPort: 8080
  replicas: 1
  selector:
    matchLabels:
      app: lable-pod-java-dev